# Fonte: Infomoney
especificacoes = {
    'TRISUL': 'tris',
    'ENERGIAS BR': 'enbr',
    'FLEURY': 'flry',
    'SANEPAR': 'sapr',
    'ITAUSA': 'itsa',
    'GERDAU': 'ggbr',
    'INVESTO WRLD': 'wrld',
    'USIMINAS': 'usim',
    'CIELO': 'ciel',
    'TAESA': 'taee',
    'WEG': 'wege',
    'VIA': 'viia',
    'MAGAZ LUIZA': 'mglu',
    'B2W': 'btow',
    'B3': 'b3sa',
    'BR MALLS': 'brml',
    'BRF': 'brfs',
    'BRASKEM': 'brkm',
    'BRADESCO': 'bbdc',
    'BANCO DO BRASIL': 'bbas',
    'BRASIL ON NM': 'bbas',
    'ITAU UNIBANCO': 'itub',
    'ITAUUNIBANCO': 'itub',
    'VALE': 'vale',
    'PETROBRAS': 'petr',
    'AMBEV': 'abev',
    'BBSEGURIDADE': 'bbse',
    'BTG PACTUAL': 'bpac',
    'CVC': 'cvcb',
    'COPASA': 'CSMG3',
    'CPFL': 'cpfe',
    'CCR': 'ccro',
    'SID NACIONAL': 'csna',
    'CYRELA': 'cyre',
    'ELETROBRAS': 'elet',
    'EMBRAER': 'embr',
    'ENAUTA': 'enat',
    'ENEVA': 'enev',
    'ENGIE': 'egie',
    'MARFRIG': 'mrfg',
    "NEOENERGIA": 'neoe',
    'ODONTOPREV': 'odpv',
    'PORTO SEGURO': 'pssa',
    'QUALICORP': 'qual',
    'LOG COM': 'logg',
    'AERIS': 'aeri',
    'ALUPAR': 'alup',
    'ITIP': 'itip',
    'IFID': 'ifid',
    'SLC AGRICOLA': 'slce',
    'B5P2': 'b5p2',
    'LOJAS RENNER': 'lren',
    'MRV': 'mrve',
    'KLABIN': 'klbn',
    'JBS': 'jbss',
    'M.DIASBRANCO': 'mdia',
    'CAMIL': 'caml',
    'HABITAT II': 'habt',
    'VINCI OFFICES': 'vino',
    'TELEF BRASIL': 'vivt',
    'MAXI RENDA': 'mxrf',
    'BB PROGRESSIVO II': 'bbpo',
    'CSHG LOGÍSTICA': 'hglg',
    'XP INDUSTRIAL': 'xpin',
    'VINCI SHOPPING CENTERS': 'visc',
    'REC RENDA IMOBILIÁRIA': 'rect',
    'SANTANDER BR': 'sanb',
    'OI': 'oibr',
    'SUL AMERICA': 'sula',
    'FII INTER IP': 'itip',
    'EZTEC': 'eztc',
    'WIZ S.A': 'wizs',
    'COPEL': 'cple',
    'EQUATORIAL': 'eqtl',
    
}